apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  type: NodePort
  ports:
  - name: {{ .Values.name }}-service
    port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    app: {{ .Values.name }}
  
